config/routes.rb
Rails.application.routes.draw do
	root to: 'static_pages#index'

	resources :static_pages, only: [:index] do
		get :search, on: :collection
	end
	resources :documents, only: [:new, :create]
end

app/models/document.rb
class Document < ActiveRecord::Base
	# We're mounting the uploader the document_attachment attribute.
	# This attribute will store the path to the attachment.
	mount_uploader :document_attachment, ::DocumentAttachmentUploader

	# Setting up ElasticSearch integration
	include Tire::Model::Search
	include Tire::Model::Callbacks

	mapping _source: { excludes: ['attachment'] } do
		indexes :id, type: 'integer'
		indexes :title
		indexes :attachment, type: 'attachment'
	end

	def attachment
		path_to_attachment = document_attachment.file.file
		Base64.encode64(open(path_to_attachment) { |file| file.read })
	end

	def to_indexed_json
		to_json(methods: [:attachment])
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	# Prevent CSRF attacks by raising an exception.
	# For APIs, you may want to use :null_session instead.
	protect_from_forgery with: :exception

	# def index
	# 	@articles = Article.search(params)
	# end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController

	def new
		@document  = Document.new
	end

	def create
		doc = params[:document]
		@document = Document.new(
			title: doc[:title],
			document_attachment: doc[:document_attachment])
		if @document.save
			redirect_to new_document_path
		else
			render 'new'
		end
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def index
	end

	def search
		@result = Document.search params[:keyword]
		# respond_to do |format|
		# 	format.html
		# 	format.js {render json: result.results}
		# end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/documents/new.html.erb
<%= form_for @document do |f| %>
	  <div class="form-group">
	      <%= f.label :title %>
	      <%= f.text_field :title, class: 'form-control' %>
	  </div>
	  <div class="form-group">
	      <%= f.label :document_attachment %>
	      <%= f.file_field :document_attachment, class: 'form-control' %>
	  </div>
	  <%= f.submit %>
<% end %>

<%= link_to "Back to home", root_path %>


</br></br>All Documents

<table>
	<thead>
		<td>No</td>
		<td>Title</td>
		<td>Type</td>
		<td>Attachment</td>
	</thead>
	<tbody>
		<% Document.all.each.with_index(1) do |doc, index| %>
			<tr>
				<td><%= index %></td>
				<td><%= doc.title %></td>
				<td><%= doc.document_type %></td>
				<td><%= doc.document_attachment %></td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TextQuery</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/static_pages/index.html.erb
<%= link_to "Add document", new_document_path %>


<%= form_tag(search_static_pages_path, method: :get) do %>
	<label for="file">Keyword : </label> <%= text_field_tag "keyword" %>
  	<%= submit_tag "search" %>
<% end %>

Result
<div id="output"></div>

app/views/static_pages/search.html.erb
<%= link_to "Back", root_path %>
<table>
	<thead>
		<td>No</td>
		<td>Title</td>
		<td>Type</td>
		<td>Attachment</td>
	</thead>
	<tbody>
		<% @result.results.each.with_index(1) do |doc, index| %>
			<tr>
				<td><%= index %></td>
				<td><%= doc.title %></td>
				<td><%= doc.document_type %></td>
				<td><%= doc.document_attachment %></td>
			</tr>
		<% end %>
	</tbody>
</table>